loki.source.syslog "proxmox" {
  listener {
    address  = "0.0.0.0:514"
    protocol = "tcp"
    labels = {
      job    = "pve_syslog",
      source = "proxmox-host",
    }
  }
  forward_to = [loki.write.default.receiver]
}

discovery.docker "docker_scrape" {
  host  = "unix:///var/run/docker.sock"
  refresh_interval = "5s"
}

discovery.relabel "docker_scrape" {
targets = discovery.docker.docker_scrape.targets
  rule {
    source_labels = ["__meta_docker_container_name"]
    regex         = "/(.*)"
    target_label  = "container"
  }
}

loki.source.docker "docker_scrape" {
  host = "unix:///var/run/docker.sock"
  targets = discovery.relabel.docker_scrape.output
  forward_to = [loki.write.default.receiver]
  relabel_rules = discovery.relabel.docker_scrape.rules
  refresh_interval = "5s"
  }

loki.write "default" {
  endpoint {
    url       = "http://192.168.0.60:3100/loki/api/v1/push"
  }
  external_labels = {}
}
