---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ observability_node_root_dir }}/pve-exporter"
    owner: ansible
    group: ansible
    mode: "0755"
    state: directory

- name: Copy PVE files
  ansible.builtin.copy:
    src: prometheus/pve.yml
    dest: "{{ observability_node_root_dir }}/pve-exporter/pve.yml"
    owner: ansible
    group: ansible
    mode: "0644"
  notify: Restart PVE-Exporter
  no_log: true
