---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ observability_node_root_dir }}/pve-exporter"
    owner: ansible
    group: ansible
    mode: "0755"
    state: directory

- name: Copy PVE files
  ansible.builtin.template:
    src: pve-exporter/pve.yml.j2
    dest: "{{ observability_node_root_dir }}/pve-exporter/pve.yml"
    owner: ansible
    group: ansible
    mode: "0640"
  notify: Restart PVE-Exporter
  no_log: true
