---
networks:
  observability:
    name: observability

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.cpu.info
    pid: host
    volumes:
      - /:/host:ro,rslave

  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:latest
    container_name: smartctl-exporter
    pull_policy: always
    restart: unless-stopped
    user: root
    cap_add:
      - SYS_RAWIO
    ports:
      - 9633:9633/tcp
    networks:
      - observability

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080/tcp
    networks:
      - observability

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7007:7007/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dozzle/data:/data
    command: agent
    networks:
      - observability

  prometheus-pve-exporter:
    container_name: pve-exporter
    image: prompve/prometheus-pve-exporter:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 9221:9221/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/prometheus:/etc/prometheus
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    pull_policy: always
    restart: unless-stopped
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
      - 514:514/tcp
    volumes:
      - /opt/alloy/alloy-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - observability    