---
- name: Media Platform
  hosts: media_platform
  become: true
  tasks:
  - name: Install and configure Docker
    ansible.builtin.import_role: 
      name: docker_base
    tags: docker

  - name: NFS Client
    block:
      - name: Install NFS-Client package
        ansible.builtin.apt:
          name: 
            - nfs-client
            - nfs-common
          state: present
          update_cache: true

      - name: Mount NFS export for docker volumes
        ansible.posix.mount:
          path: /opt/media_platform
          src: "{{ nfs_server_host }}:/exports/media_platform"
          fstype: nfs4
          opts: "rw,hard,timeo=600,retrans=2,_netdev"
          state: mounted
    tags: nfs_mount
  
  - name: Deploy Media Platform
    ansible.builtin.import_role: 
      name: media_platform
    tags: media_platform
