---
- name: Observability Stack Control
  hosts: observability_control
  become: true
  force_handlers: true
  roles:
    #- role: docker_base
    - role: observability_control
      vars:
        observability_control_pve_node_ip: "{{ hostvars['monitoring-1']['ansible_host'] }}"
