---
- name: Observability Stack Control
  hosts: observability_pve
  become: true
  force_handlers: true
  vars:
    observability_node_loki_remote_url: hostvars[observability_control][0]['loki_remote_url']
  roles:
    - role: docker_base
    - role: observability_node