---
- name: Observability Stack Control
  hosts: observability_control
  become: true
  force_handlers: true
  tasks:
    - name: Deploy docker_base
      ansible.builtin.import_role:
        name: docker_base
      tags: docker

    - name: Deploy observability_control
      ansible.builtin.import_role:
        name: observability_control
      tags: observability
