---
- name: Observability Stack Control
  hosts: observability_control
  become: true
  force_handlers: true
  tasks:
    # - name: Import docker_base role
    #   ansible.builtin.import_role:
    #     name: docker_base
    
    - name: Import observaiblity control role
      ansible.builtin.import_role:
        name: observability_control
