---
- name: Observability Stack Control
  hosts: observability_pve
  become: true
  force_handlers: true
  tasks:
    - name: Deploy docker_base
      ansible.builtin.import_role:
        name: docker_base
      tags: docker

    - name: Deploy observability_node
      ansible.builtin.import_role:
        name: observability_node
      tags: observability
