---
- name: Setup observability control
  ansible.builtin.import_playbook: observability_control.yml

- name: Setup observability node
  ansible.builtin.import_playbook: observability_pve.yml

- name: Setup observability node
  ansible.builtin.import_playbook: observability_nodes.yml
