---
- name: Ensure Bazarr config directory exists
  ansible.builtin.file:
    path: "{{ media_platform_config_dir }}/bazarr/data/config"
    state: directory
    owner: "{{ media_platform_user }}"
    group: "{{ media_platform_group }}"
    mode: "2770"

- name: Place bazarr config.yml
  ansible.builtin.template:
    src: bazarr_config.yml.j2
    dest: "{{ media_platform_config_dir }}/bazarr/data/config/config.yaml"
    owner: "{{ media_platform_user }}"
    group: "{{ media_platform_group }}"
    mode: "0640"
    force: false
  no_log: true
  notify: Restart Bazarr
