---
- name: Ensure Bazaar config directory exists
  ansible.builtin.file:
    path: /opt/media_platform/bazarr/data/config
    state: directory
    owner: "{{ media_platform_user }}"
    group: "{{ media_platform_group }}"
    mode: "02770"

- name: Place bazarr config.yml
  ansible.builtin.template:
    src: bazarr_config.yml.j2
    dest: /opt/media_platform/bazarr/data/config/config.yaml
    owner: "{{ media_platform_user }}"
    group: "{{ media_platform_group }}"
    mode: "02770"
    force: false
  no_log: true
  notify: Restart Bazarr
