---
- name: Ensure configarr folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ media_platform_user }}"
    group: "{{ media_platform_group }}"
    mode: "2770"
    state: directory
  loop:
    - "{{ media_platform_root_dir }}/configarr/data/config"
    - "{{ media_platform_root_dir }}/configarr/data/repos"
    - "{{ media_platform_root_dir }}/configarr/data/cfs"
    - "{{ media_platform_root_dir }}/configarr/data/templates"

- name: Place configarr config
  ansible.builtin.template:
    src: configarr.yml.j2
    dest: "{{ media_platform_root_dir }}/configarr/data/config/config.yml"
    owner: "{{ media_platform_user }}"
    group: "{{ media_platform_group }}"
    mode: "0440"
  notify: Restart configarr
