---
- name: Install and Configure SOPS
  hosts: localhost
  become: true
  tags: sops
  tasks:
    - name: Install SOPS on localhost
      ansible.builtin.include_role:
        name: community.sops.install
      vars:
        sops_install_on_localhost: true
