---
observability_node_cluster_name: homelab
observability_node_node_host_ip:
observability_node_pve_node_ip:
observability_node_root_dir: /opt

observability_node_alloy_name: alloy
observability_node_alloy_con_port: 12345
observability_node_alloy_host_port: 12345
observability_node_alloy_journal_enabled: false

observability_node_cadvisor_name: cadvisor
observability_node_cadvisor_host_port: 8080

observability_node_dozzle_name: dozzle
observability_node_dozzle_agent_port: 7007
observability_node_dozzle_agent_pve_ip: ""
observability_node_dozzle_host_port: 7070

observability_node_grafana_name: grafana
observability_node_grafana_host_port: 3000

observability_node_loki_name: loki
observability_node_loki_host_port: 3100
observability_node_loki_remote_url:

observability_node_node_exporter_name: node-exporter
observability_node_node_exporter_host_port: 9100

observability_node_prometheus_name: prometheus
observability_node_prometheus_host_port: 9090

observability_node_pve_exporter_name: pve-exporter
observability_node_pve_exporter_host_port: 9221

observability_node_smartctl_exporter_name: smartctl-exporter
observability_node_smartctl_exporter_host_port: 9633
